# https://ocaml.org/learn/tutorials/99problems.html problems 32-34 
let rec gcd = (a,b) => if (b == 0) {a} else {gcd (b,a % b)}

let coprime = (a,b) => gcd (a,b) == 1

let phi = (n) => {
    let rec count_coprime = (acc,d) =>
      if (d < n) {
	    count_coprime(if (coprime(n,d)) {acc+1} else {acc},d+1)
      } else {
	    acc
	  }
    if (n == 1) {1} else {count_coprime(0,1)}
}

print(phi(10))

export phi