// Generated by js_of_ocaml 3.8.0
(function(a){"use strict";var
an=" : flags Open_text and Open_binary are not compatible",$="Sys_error",am="Invalid_argument",_=0xf0,al=0x800,F="jsError",t=1024,ak="End_of_file",j=0x80,aj="Failure",Y="Undefined_recursive_module",Z=" : flags Open_rdonly and Open_wronly are not compatible",X="([^/]*)",W=512,ai="Stack_overflow",e="",E="^",U=" : file already exists",V=0xe0,p=0x3f,T=0xdfff,ah="Not_found",S="Assert_failure",m="/",D=128,ae="Sys_blocked_io",af="fd ",ag=0xdc00,R="Out_of_memory",ad="Match_failure",g=248,ab="Division_by_zero",ac="static/",aa=252,a6=0;function
v(){return a6++}function
a9(b,a){throw[0,b,a]}function
ba(b,a){if(b==0)return e;if(a.repeat)return a.repeat(b);var
d=e,c=0;for(;;){if(b&1)d+=a;b>>=1;if(b==0)return d;a+=a;c++;if(c==9)a.slice(0,1)}}function
J(c,b,a){var
d=String.fromCharCode;if(b==0&&a<=4096&&a==c.length)return d.apply(null,c);var
f=e;for(;0<a;b+=t,a-=t)f+=d.apply(null,c.slice(b,b+Math.min(a,t)));return f}function
as(a){if(a.t==2)a.c+=ba(a.l-a.c.length,"\0");else
a.c=J(a.c,0,a.c.length);a.t=0}function
aD(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
K(f){for(var
l=e,c=e,h,g,i,a,b=0,k=f.length;b<k;b++){g=f.charCodeAt(b);if(g<j){for(var
d=b+1;d<k&&(g=f.charCodeAt(d))<j;d++);if(d-b>W){c.substr(0,1);l+=c;c=e;l+=f.slice(b,d)}else
c+=f.slice(b,d);if(d==k)break;b=d}a=1;if(++b<k&&((i=f.charCodeAt(b))&-64)==D){h=i+(g<<6);if(g<V){a=h-0x3080;if(a<j)a=1}else{a=2;if(++b<k&&((i=f.charCodeAt(b))&-64)==D){h=i+(h<<6);if(g<_){a=h-0xe2080;if(a<al||a>=0xd7ff&&a<0xe000)a=2}else{a=3;if(++b<k&&((i=f.charCodeAt(b))&-64)==D&&g<0xf5){a=i-0x3c82080+(h<<6);if(a<0x10000||a>0x10ffff)a=3}}}}}if(a<4){b-=a;c+="\ufffd"}else
if(a>0xffff)c+=String.fromCharCode(0xd7c0+(a>>10),ag+(a&0x3FF));else
c+=String.fromCharCode(a);if(c.length>t){c.substr(0,1);l+=c;c=e}}return l+c}function
n(c,a,b){this.t=c;this.c=a;this.l=b}n.prototype.toString=function(){switch(this.t){case
9:return this.c;default:as(this);case
0:if(aD(this.c)){this.t=9;return this.c}this.t=8;case
8:return this.c}};n.prototype.toUtf16=function(){var
a=this.toString();if(this.t==9)return a;return K(a)};n.prototype.slice=function(){var
a=this.t==4?this.c.slice():this.c;return new
n(this.t,a,this.l)};function
aq(a){return new
n(0,a,a.length)}function
d(a){return aq(a)}function
I(b,a){a9(b,d(a))}var
c=[0];function
aU(a){I(c.Failure,a)}function
aZ(a){return a.toUtf16()}if(a.process&&a.process.cwd)var
u=a.process.cwd().replace(/\\/g,m);else
var
u="/static";if(u.slice(-1)!==m)u+=m;function
a0(a){a=aZ(a);if(a.charCodeAt(0)!=47)a=u+a;var
d=a.split(m),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(e);break;default:b.push(d[c]);break}b.orig=a;return b}function
H(a){return a
instanceof
n}function
av(a){return H(a)}function
aQ(a){return new
n(4,a,a.length)}function
y(a){return a}function
bd(f){for(var
g=e,b=g,a,i,c=0,h=f.length;c<h;c++){a=f.charCodeAt(c);if(a<j){for(var
d=c+1;d<h&&(a=f.charCodeAt(d))<j;d++);if(d-c>W){b.substr(0,1);g+=b;b=e;g+=f.slice(c,d)}else
b+=f.slice(c,d);if(d==h)break;c=d}if(a<al){b+=String.fromCharCode(0xc0|a>>6);b+=String.fromCharCode(j|a&p)}else
if(a<0xd800||a>=T)b+=String.fromCharCode(V|a>>12,j|a>>6&p,j|a&p);else
if(a>=0xdbff||c+1==h||(i=f.charCodeAt(c+1))<ag||i>T)b+="\xef\xbf\xbd";else{c++;a=(a<<10)+i-0x35fdc00;b+=String.fromCharCode(_|a>>18,j|a>>12&p,j|a>>6&p,j|a&p)}if(b.length>t){b.substr(0,1);g+=b;b=e}}return g+b}function
aR(a){var
b=9;if(!aD(a))b=8,a=bd(a);return new
n(b,a,a.length)}function
A(a){return aR(a)}function
b(a){I(c.Sys_error,a)}function
z(a){if((a.t&6)!=0)as(a);return a.c}function
a8(a){a=z(a);b(a+": No such file or directory")}function
au(a){I(c.Invalid_argument,a)}function
ap(){au("index out of bounds")}function
ar(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
aP(b,a){if(a>>>0>=b.l)ap();return ar(b,a)}function
r(a){if(a<0)au("Bytes.create");return new
n(a?2:9,e,a)}function
aw(a){return a.l}function
G(c){if(a.Uint8Array)var
d=new(a.Uint8Array)(c.l);else
var
d=new
Array(c.l);var
f=c.c,e=f.length,b=0;for(;b<e;b++)d[b]=f.charCodeAt(b);for(e=c.l;b<e;b++)d[b]=0;c.c=d;c.t=4;return d}function
x(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?J(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?J(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)G(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
aO(a,b,c,d,e){x(y(a),b,c,d,e);return 0}function
ao(){}function
f(a){this.data=a}f.prototype=new
ao();f.prototype.truncate=function(a){var
b=this.data;this.data=r(a|0);x(b,0,this.data,0,a)};f.prototype.length=function(){return aw(this.data)};f.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=r(b+a),f=this.data;this.data=e;x(f,0,this.data,0,c)}aO(d,g,this.data,b,a);return 0};f.prototype.read=function(c,a,d,b){var
e=this.length();x(this.data,c,a,d,b);return 0};f.prototype.read_one=function(a){return aP(this.data,a)};f.prototype.close=function(){};f.prototype.constructor=f;function
h(b,a){this.content={};this.root=b;this.lookupFun=a}h.prototype.nm=function(a){return this.root+a};h.prototype.lookup=function(a){if(!this.content[a]&&this.lookupFun){var
b=this.lookupFun(d(this.root),d(a));if(b!==0)this.content[a]=new
f(y(b[1]))}};h.prototype.exists=function(a){if(a==e)return 1;var
c=a+m,d=new
RegExp(E+c);for(var
b
in
this.content)if(b.match(d))return 1;this.lookup(a);return this.content[a]?1:0};h.prototype.readdir=function(c){var
g=c==e?e:c+m,h=new
RegExp(E+g+X),d={},b=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!d[a[1]]){d[a[1]]=true;b.push(a[1])}}return b};h.prototype.is_dir=function(a){var
d=a==e?e:a+m,f=new
RegExp(E+d+X),g=[];for(var
c
in
this.content){var
b=c.match(f);if(b)return 1}return 0};h.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};h.prototype.open=function(a,c){if(c.rdonly&&c.wronly)b(this.nm(a)+Z);if(c.text&&c.binary)b(this.nm(a)+an);this.lookup(a);if(this.content[a]){if(this.is_dir(a))b(this.nm(a)+" : is a directory");if(c.create&&c.excl)b(this.nm(a)+U);var
d=this.content[a];if(c.truncate)d.truncate();return d}else
if(c.create){this.content[a]=new
f(r(0));return this.content[a]}else
a8(this.nm(a))};h.prototype.register=function(c,a){if(this.content[c])b(this.nm(c)+U);if(H(a))this.content[c]=new
f(a);if(av(a))this.content[c]=new
f(y(a));else
if(a
instanceof
Array)this.content[c]=new
f(aQ(a));else
if(typeof
a==="string")this.content[c]=new
f(aq(a));else
if(a.toString){var
d=y(A(a.toString()));this.content[c]=new
f(d)}else
b(this.nm(c)+" : registering file with invalid content type")};h.prototype.constructor=h;function
ay(a){return aw(a)}function
bb(b,a){return ar(b,a)}function
aN(d){var
c=ay(d),b=new
Array(c),a=0;for(;a<c;a++)b[a]=bb(d,a);return b}function
aM(a){if(a.t!=4)G(a);return a.c}function
aT(a,c,b){b&=0xff;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}G(a)}a.c[c]=b;return 0}function
aS(b,a,c){if(a>>>0>=b.l)ap();return aT(b,a,c)}function
l(a){this.fs=require("fs");this.fd=a}l.prototype=new
ao();l.prototype.truncate=function(a){try{this.fs.ftruncateSync(this.fd,a|0)}catch(a){b(a.toString())}};l.prototype.length=function(){try{return this.fs.fstatSync(this.fd).size}catch(a){b(a.toString())}};l.prototype.write=function(h,d,e,g){var
c=aN(d);if(!(c
instanceof
a.Uint8Array))c=new(a.Uint8Array)(c);var
f=a.Buffer.from(c);try{this.fs.writeSync(this.fd,f,e,g,h)}catch(a){b(a.toString())}return 0};l.prototype.read=function(i,f,e,h){var
c=aM(f);if(!(c
instanceof
a.Uint8Array))c=new(a.Uint8Array)(c);var
g=a.Buffer.from(c);try{this.fs.readSync(this.fd,g,e,h,i)}catch(a){b(a.toString())}for(var
d=0;d<h;d++)aS(f,e+d,g[e+d]);return 0};l.prototype.read_one=function(e){var
d=new(a.Uint8Array)(1),c=a.Buffer.from(d);try{this.fs.readSync(this.fd,c,0,1,e)}catch(a){b(a.toString())}return c[0]};l.prototype.close=function(){try{this.fs.closeSync(this.fd)}catch(a){b(a.toString())}};l.prototype.constructor=l;function
k(a){this.fs=require("fs");this.root=a}k.prototype.nm=function(a){return this.root+a};k.prototype.exists=function(a){try{return this.fs.existsSync(this.nm(a))?1:0}catch(a){b(a.toString())}};k.prototype.readdir=function(a){try{return this.fs.readdirSync(this.nm(a))}catch(a){b(a.toString())}};k.prototype.is_dir=function(a){try{return this.fs.statSync(this.nm(a)).isDirectory()?1:0}catch(a){b(a.toString())}};k.prototype.unlink=function(a){try{var
c=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a))}catch(a){b(a.toString())}return c};k.prototype.open=function(g,d){var
a=require("constants"),c=0;for(var
f
in
d)switch(f){case"rdonly":c|=a.O_RDONLY;break;case"wronly":c|=a.O_WRONLY;break;case"append":c|=a.O_WRONLY|a.O_APPEND;break;case"create":c|=a.O_CREAT;break;case"truncate":c|=a.O_TRUNC;break;case"excl":c|=a.O_EXCL;break;case"binary":c|=a.O_BINARY;break;case"text":c|=a.O_TEXT;break;case"nonblock":c|=a.O_NONBLOCK;break}try{var
e=this.fs.openSync(this.nm(g),c);return new
l(e)}catch(a){b(a.toString())}};k.prototype.rename=function(c,a){try{this.fs.renameSync(this.nm(c),this.nm(a))}catch(a){b(a.toString())}};k.prototype.constructor=k;var
s=u.match(/[^\/]*\//)[0];function
bf(){return typeof
a.process!=="undefined"&&typeof
a.process.versions!=="undefined"&&typeof
a.process.versions.node!=="undefined"&&a.process.platform!=="browser"}var
w=[];if(bf())w.push({path:s,device:new
k(s)});else
w.push({path:s,device:new
h(s)});w.push({path:s+ac,device:new
h(s+ac)});function
aE(b){var
f=a0(b),b=f.join(m),e=b+m,c;for(var
d=0;d<w.length;d++){var
a=w[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
at(b,a){var
b=typeof
b=="string"?d(b):b,a=typeof
a=="string"?d(a):a,c=aE(b);if(!c.device.register)aU("cannot register file");c.device.register(c.rest,a);return 0}function
aV(){var
c=a.caml_fs_tmp;if(c)for(var
b=0;b<c.length;b++)at(c[b].name,c[b].content);a.caml_create_file=at;a.caml_fs_tmp=[];return 0}function
aW(){return typeof
module!=="undefined"&&module&&module.exports?module.exports:a}function
q(c,a){if(c.fun)return q(c.fun,a);if(typeof
c!=="function")return c;var
b=c.length|0;if(b===0)return c.apply(null,a);var
e=a.length|0,d=b-e|0;if(d==0)return c.apply(null,a);else
if(d<0)return q(c.apply(null,a.slice(0,b)),a.slice(b));else
return function(){var
e=arguments.length==0?1:arguments.length,d=new
Array(a.length+e);for(var
b=0;b<a.length;b++)d[b]=a[b];for(var
b=0;b<arguments.length;b++)d[a.length+b]=arguments[b];return q(c,d)}}function
aX(d){return function(){var
b=arguments.length;if(b>0){var
c=new
Array(b);for(var
a=0;a<b;a++)c[a]=arguments[a];return q(d,c)}else
return q(d,[undefined])}}function
aY(d){return function(){var
c=arguments.length,b=new
Array(c+1);b[0]=this;for(var
a=0;a<c;a++)b[a+1]=arguments[a];return q(d,b)}}var
o=new
Array();function
a1(f){var
a=o[f];if(!a.opened)b("Cannot flush a closed channel");if(!a.buffer||a.buffer==e)return 0;if(a.fd&&c.fds[a.fd]&&c.fds[a.fd].output){var
d=c.fds[a.fd].output;switch(d.length){case
2:d(f,a.buffer);break;default:d(a.buffer)}}a.buffer=e;return 0}function
aC(e,f){var
a=o[e],c=d(f),b=ay(c);a.file.write(a.offset,c,0,b);a.offset+=b;return 0}function
bg(b){var
b=K(b),c=a;if(c.process&&c.process.stdout&&c.process.stdout.write)c.process.stderr.write(b);else{if(b.charCodeAt(b.length-1)==10)b=b.substr(0,b.length-1);var
d=c.console;d&&d.error&&d.error(b)}}function
bh(b){var
b=K(b),c=a;if(c.process&&c.process.stdout&&c.process.stdout.write)c.process.stdout.write(b);else{if(b.charCodeAt(b.length-1)==10)b=b.substr(0,b.length-1);var
d=c.console;d&&d.log&&d.log(b)}}function
B(d,f,e,a){if(c.fds===undefined)c.fds=new
Array();a=a?a:{};var
b={};b.file=e;b.offset=a.append?e.length():0;b.flags=a;b.output=f;c.fds[d]=b;if(!c.fd_last_idx||d>c.fd_last_idx)c.fd_last_idx=d;return d}function
bi(e,d,i){var
a={};while(d){switch(d[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}d=d[2]}if(a.rdonly&&a.wronly)b(z(e)+Z);if(a.text&&a.binary)b(z(e)+an);var
f=aE(e),g=f.device.open(f.rest,a),h=c.fd_last_idx?c.fd_last_idx:0;return B(h+1,aC,g,a)}B(0,aC,new
f(r(0)));B(1,bh,new
f(r(0)));B(2,bg,new
f(r(0)));function
a2(e){var
d=c.fds[e];if(d.flags.wronly)b(af+e+" is writeonly");var
a={file:d.file,offset:d.offset,fd:e,opened:true,out:false,refill:null};o[a.fd]=a;return a.fd}function
ax(f){var
d=c.fds[f];if(d.flags.rdonly)b(af+f+" is readonly");var
a={file:d.file,offset:d.offset,fd:f,opened:true,out:true,buffer:e};o[a.fd]=a;return a.fd}function
a3(){var
b=0;for(var
a=0;a<o.length;a++)if(o[a]&&o[a].opened&&o[a].out)b=[0,o[a].fd,b];return b}function
a7(a){throw a}function
a_(){a7(c.Division_by_zero)}function
a4(b,a){if(a==0)a_();return b%a}function
a5(a){if(a
instanceof
Array&&a[0]==a[0]>>>0)return a[0];else
if(H(a))return aa;else
if(av(a))return aa;else
if(a
instanceof
Function||typeof
a=="function")return 247;else
if(a&&a.caml_custom)return 255;else
return 1000}function
i(d,e,b){if(b&&a.toplevelReloc)d=a.toplevelReloc(b);c[d+1]=e;if(b)c[b]=e}var
aA={};function
a$(a,b){aA[z(a)]=b;return 0}function
bc(){return[0,d("js_of_ocaml")]}function
aB(a){return a}function
az(a){return aA[a]}function
be(b){if(b
instanceof
Array)return b;if(a.RangeError&&b
instanceof
a.RangeError&&b.message&&b.message.match(/maximum call stack/i))return aB(c.Stack_overflow);if(a.InternalError&&b
instanceof
a.InternalError&&b.message&&b.message.match(/too much recursion/i))return aB(c.Stack_overflow);if(b
instanceof
a.Error&&az(F))return[0,az(F),b];return[0,c.Failure,A(String(b))]}aV();var
L=[g,d($),-2];i(11,[g,d(Y),-12],Y);i(10,[g,d(S),-11],S);i(9,[g,d(ae),-10],ae);i(8,[g,d(ai),-9],ai);i(7,[g,d(ad),-8],ad);i(6,[g,d(ah),-7],ah);i(5,[g,d(ab),-6],ab);i(4,[g,d(ak),-5],ak);i(3,[g,d(am),-4],am);i(2,[g,d(aj),-3],aj);i(1,L,$);i(0,[g,d(R),-1],R);v(0);a2(0);ax(1);ax(2);v(0);var
aK=d("Js_of_ocaml__Js.Error");typeof
bc(0)==="number";v(0);v(0);var
M=[0,0];function
N(a){M[1]=[0,a,M[1]];return 0}var
O=a,aH=O.Object,aJ=O.Array,P=[g,aK,v(0)],C=[0,P,{}],aG=a5(C)===g?C:C[1];a$(d(F),aG);(function(a){throw a});N(function(a){return a[1]===P?[0,A(a[2].toString())]:0});N(function(a){return a
instanceof
aJ?0:[0,A(a.toString())]});function
aL(e){if(1===e)return 1;var
c=0,b=1;a:for(;;){if(b<e){var
d=e,a=b,g=b+1|0;for(;;){if(0===a){var
h=1===d?c+1|0:c,c=h,b=g;continue a}var
f=a4(d,a),d=a,a=f;continue}}return c}}var
Q={"phi":aY(function(a){return aL})},aI=aH.keys(Q);aI.forEach(aX(function(a,d,c){var
b=Q[a];return aW(0)[a]=b}));function
aF(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{a1(d)}catch(a){a=be(a);if(a[1]!==L)throw a;var
e=a}var
a=c;continue}return 0}}aF(a3(0));return}(function(){return this}()));
